version: '3.5'
services:
        web:
                build: .
                ports: 
                - "9022:22"
                - "9080:80"
                - "9443:443"
                - "9100-9110:9100-9110"
                volumes:
                - /data/imagenes-biologicas/web:/web

